### ISSUE TITLE
Hapi-sequelizejs  dependency of @hapi/joi 

### ISSUE THREAD

**Issue by vollaregroup** [valtlfelipe/hapi-sequelizejs#109]
I have a node application with hapi and I use hapi-swagger which no longer supports @hap  joi (deprecated). Hapi-sequelizejs is dependent on @hapi/joi and therefore the app generates the error "Error: Cannot mix different versions of joi schemas"
The solution would be to eliminate the dependence on Hapi-sequelizejs @hapi/joi
Is there a prediction to solve this problem?
In my case, I made the changes myself and it works, but I had to create a customized version of Hapi-sequelizejs.

**Comment by valtlfelipe** [comment]
Published v4.4.0 which fixes this
