### ISSUE TITLE
Improve README/Documentation

### ISSUE THREAD

**Issue by valtlfelipe** [valtlfelipe/hapi-sequelizejs#13]

**Comment by Nargonath** [comment]
Do you have something in mind?

**Comment by valtlfelipe** [comment]
I think to add a better description for all of the options keys, what the property is, what type it is, and so on. Something like [this](https://github.com/dwyl/hapi-auth-jwt2#documentation).

Provide more/better examples, maybe a folder with example code inside.

How to run tests and contribute.

More badges (npm, hapi and sequelize versions supported).

Of course I'm open to suggestions.

**Comment by nejc001** [comment]
In "Configuration" documentation code part, it should be 
`server.register({
plugin: require('something')
})`
and not
`server.register({
register: require('something')
})`

Otherwise you get an error:  "register" must be a Function

Im using hapi 17.4.0.

**Comment by valtlfelipe** [comment]
Thanks @nejc001! Good catch
