### ISSUE TITLE
Registering to onClose server events to shutdown the database connections

### ISSUE THREAD

**Issue by Nargonath** [valtlfelipe/hapi-sequelizejs#16]
When doing tests, even after my test runner has finished running the tests suites it keeps hanging because  even though I do `server.stop()` the database pool connection is not closed. I think we should register to the `server.on('close', ...)` event and clean that up.

By the way I'm using Jest as my test runner.

I'll work on a PR if you are ok with it.

**Comment by valtlfelipe** [comment]
Sounds fair! Before shutting down the server, we should close all database connections before it. Implementing this in the plugin, would be awesome.

You may work on a PR if you like, I appreciate it.
