### ISSUE TITLE
require db model outside a handler

### ISSUE THREAD

**Issue by gigioSouza** [valtlfelipe/hapi-sequelizejs#18]
Is there a way to require the models outside a handler?
Ex:
**user.handler.js**
```
const UserService = require('./../services/user.service');

module.exports = {
  create,
  get
}

function create(request, h) {
  return UserService.create(request.payload);
}
function get(request, h) {
  return UserService.get(request.params.id);
}
```

**user.service.js**
```
const UserModel = require('./../models/user.model');

module.exports = {
  save,
  get
}

function save(user) {
  return UserModel.create(user);
}
function get(id) {
  return UserModel.findById(id);
}
```

Because currently I'm doing this:
**user.handler.js**
```
const UserService = require('./../services/user.service');

module.exports = {
  create,
  get
}

function create(request, h) {
  return UserService.create(request.getDb('pg'), request.payload);
}
function get(request, h) {
  return UserService.get(request.getDb('pg'), request.params.id);
}
```

**user.service.js**
```
module.exports = {
  save,
  get
}

function getModel(db) {
  return db.getModel('User');
}
function save(db, user) {
  return getModel(db).create(user);
}
function get(db, id) {
  return getModel(db).findById(id);
}
```

**Comment by Nargonath** [comment]
As of now I don't think there is a way to get the db object outside of a handler function because `getDb()` is only attached to the request object. Feel free to create a PR. The source code is not really difficult to grasp.

**Comment by jberall** [comment]
If you pass the server or can access it.
You should be able to find the models

**Comment by valtlfelipe** [comment]
You can also the `onConnect` hook, and save the instance in a global variable, sou you can access it any where. It is not the best practice, but would work.

It's not documented, but see the test https://github.com/valtlfelipe/hapi-sequelizejs/blob/master/test/index.js#L223

**Comment by gigioSouza** [comment]
Well, I did a workaround setting up a Singleton with my db connection. I'll study your source code to implement a PR.

**Comment by valtlfelipe** [comment]
That's ok! Feel free to contribute ;)
