### ISSUE TITLE
Question Catch DatabaseError when thrown

### ISSUE THREAD

**Issue by jberall** [valtlfelipe/hapi-sequelizejs#23]
I would like to log Database Errors at the server level.
Does anyone have any example?
Thanks,
Jonathan

**Comment by valtlfelipe** [comment]
Hi @jberall 

What do you mean? Can you give an example?

**Comment by jberall** [comment]
db.getModel('user').findall()
.then(response => ...)
.catch(err => db error)

It would be nice if their was a way to log the .catch globally.
I had an instance where my model and table didn't match and I spent a ton of time.
Also when users have errors the info they give is not very helpful.
I looked at the logging but I believe that sends all the sql queries.

**Comment by valtlfelipe** [comment]
This is something that is related specifically to `sequelize` lib, and in my opinion, should not have nothing todo with this plugin.
Please see https://github.com/sequelize/sequelize/issues/1707.

Following their example, using this plugin, you can do like this:
```js
// initialize sequelize externally
const sequelize = new Sequelize(config, opts);
sequelize.query = async function () {
	// ...
};

// then register the plugin with hapi
server.register([
    {
        plugin: require('hapi-sequelizejs'),
        options: [
            {
                name: 'dbname', // identifier
                sequelize, // sequelize instance
            },
        ],
    },
]);
```

If you need something else, please let me know.
