### ISSUE TITLE
Question Testing

### ISSUE THREAD

**Issue by jberall** [valtlfelipe/hapi-sequelizejs#27]
I'm looking at using sequelize-mocking for testing.
Does anyone have any experience with any mocking packages?
Thanks,
Jonathan

**Comment by valtlfelipe** [comment]
Hi @jberall 
I like to use `jest` to test my apps, and the mock works very well. But I mock the sequelize instance, and not the hapi-sequelizejs plugin.

If you need help for the sequelize, please open an issue at their repo [here](https://github.com/sequelize/sequelize/issues).

If you need additional help, with this plugin, please feel free to reopen this issue.

A short example using jest (not tested):
```js
jest.mock('sequelize', () => {
	const findOneMock = jest.fn();
	return jest.fn().mockImplementation(() => {
		return {
			models: {
				User: {
					findOne: findOneMock
				}
			}
		}
	});
});
```
