### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by schmanat** [valtlfelipe/hapi-sequelizejs#33]
First of all thanks for this plugin, but I'm really new to Node.js Hapi and Sequelize, so I need help :)

Is there an example how to use the plugin. I would like to use the plugin and share the connection over all necessaries models. Whats the right way to archive this.

Generally thanks for creating this plugin.

**Comment by valtlfelipe** [comment]
Hi @schmanat!

It's a pleasure 😄 

This plugin will help you to use Sequelize with hapi.js. With that said, you will need to [setup an hapi.js instance](https://hapi.dev/tutorials/?lang=en_US#overview) and then configure Sequelize to use on this plugin like [described in the docs](https://github.com/valtlfelipe/hapi-sequelizejs#configuration).

With this you will have all models setup, and you can use the connection in all your hapi.js handlers.

Does this help you?

**Comment by schmanat** [comment]
Thank you for your help. It would be great, if its possible to provide an folder with examples.
I give it a try. If I have success i would make a pull request with an example. Is that ok for you?

**Comment by valtlfelipe** [comment]
Awesome, sounds good to me!
Please let me know if you need further help.

**Comment by valtlfelipe** [comment]
@schmanat I just realized, you can use some of the test cases to see an example.
Have a look at https://github.com/valtlfelipe/hapi-sequelizejs/tree/master/test.
