### ISSUE TITLE
Plugin not detecting models

### ISSUE THREAD

**Issue by MrDHat** [valtlfelipe/hapi-sequelizejs#4]
I am using postgres with sequelize. Here is what my code looks like:

```js
server.register([
  {
    register: require('hapi-sequelizejs'), // eslint-disable-line global-require
    options: {
      name: Config.db.name,
      models: ['./models/*.js'],
      sequelize: new Sequelize(Config.db.name, Config.db.username, Config.db.password, {
        host: Config.db.host,
        dialect: 'postgres',
      }),
      sync: true,
    },
  },
])
```
When I log `req.server.plugins['hapi-sequelizejs'][Config.db.name].getModels()` I get an empty object. Here is what my model definition looks like:

```js
module.exports = (sequelize, DataTypes) => {
  const schema = {
    id: {
      type: DataTypes.UUIDV4,
      primaryKey: true,
    },
    name: DataTypes.STRING,
    email: DataTypes.STRING,
    gender: DataTypes.ENUM('male', 'female', 'other'),
  };
  return sequelize.define('User', schema);
};
```

Not sure what the problem is here. 

P.S. I have confirmed that the location of the models glob is correct by manually using `node-glob`.

**Comment by antonsamper** [comment]
Try updating your `models` property value to: 
```javascript
models: [`${__dirname}/models/*.js`],
```
Or if your models are in separate sub folders e.g. `models/user/index.js`, then try this:
```javascript
models: [`${__dirname}/models/**/*.js`],
```

If the above doesn't work, can you share your folder structure?

**Comment by MrDHat** [comment]
Ah, that worked. Thanks!

**Comment by rogeriomq** [comment]
I solved with:
`models: ['**/sequelize/models/**.js'],`

**Comment by arbisyarifudin** [comment]
Hi, I am facing the same issue here.

Here is my code:
```
const sequelize = new Sequelize('mydatabasename', 'postgres', 'root', {
    host: 'localhost',
    port: '5432',
    dialect: 'postgres'
  })
  await server.register([
    {
      plugin: HapiSequelize,
      options: [
        {
          name: 'db', // identifier
          models: [__dirname + '/models/**/*.js'], // paths/globs to model files
          // ignoredModels: [__dirname + '/models/**/*.js'], // OPTIONAL: paths/globs to ignore files
          sequelize: sequelize, // sequelize instance
          sync: true, // sync models - default false
          // forceSync: false // force sync (drops tables) - default false
        }
      ]
    }
  ])
  
  console.log(HapiSequelize.instances.getModel('db','Contact')) // return error 
```

it's return **Error: hapi-sequelizejs cannot find the Contact model**

here is my directory structure:
![image](https://user-images.githubusercontent.com/33389879/206871067-62e350c0-af6b-4dfb-a1ec-56c2e1632393.png)

and this is my contact model:
![image](https://user-images.githubusercontent.com/33389879/206871127-043404e0-67ef-4327-9233-96ff59d7ba77.png)

**Comment by valtlfelipe** [comment]
@arbisyarifudin in which file did you instantiated the sequelize? Also could you try to export the model using `module.exports`?
