### ISSUE TITLE
Support hapi v17

### ISSUE THREAD

**Issue by valtlfelipe** [valtlfelipe/hapi-sequelizejs#7]

**Comment by failpunk** [comment]
It's pretty straight forward.  I have a fork running with the updates already:
https://github.com/failpunk/hapi-sequelizejs/commit/59efa766c3f5fd75c6869e841c357c87d3768192

Haven't touched the test though.

**Comment by valtlfelipe** [comment]
@failpunk Feel free to open a PR, I will be more than happy to merge this whens its ready. 😄 

I have to confess, I haven't much time to work on this.

If you need some help, please let me know.

**Comment by stevewillard** [comment]
What's the status of this? Would love to see v17 support.

**Comment by Nargonath** [comment]
I'd be ready to help as well with the migration to v17

**Comment by valtlfelipe** [comment]
Guys, I had no time to look at this! 😞

I promise I will dedicate some of my time to maintain this. 
My intent of creating this, was because of no support of the other author, and now I'm kind of doing the same.

I will be more than happy to see an PR, and be able to merge it. Also, please let me know if you need some help.

**Comment by Nargonath** [comment]
@valtlfelipe No big deal. We all know how it is, don't worry. I started to work on a PR, I should finish it during next week.

**Comment by valtlfelipe** [comment]
Guys,

Released [1.0.0](https://github.com/valtlfelipe/hapi-sequelizejs/releases/tag/1.0.0) with hapi v17 support, thanks to @Nargonath!

Please enjoy 😄

**Comment by Nargonath** [comment]
You are welcome. Was a fun thing to do and I'm happy to help.
