### ISSUE TITLE
Consider adding precommit hook with prettier

### ISSUE THREAD

**Issue by Nargonath** [valtlfelipe/hapi-sequelizejs#9]
I'm working on the rewrite for hapi v17 and I wonder if you don't mind adding a precommit hook to automatically format the codebase using prettier.

What do you think?

**Comment by valtlfelipe** [comment]
Hi @Nargonath!

Yes, awesome idea! Just please maintain some of the patter already applied.
See https://github.com/valtlfelipe/hapi-sequelizejs/blob/master/.editorconfig for example.

Thanks for your support 😉

**Comment by Nargonath** [comment]
Alright. I'll make sure to respect the setting in editorconfig. ;) Thanks for letting me know.
